# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pdp_iop_grpc/request.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'pdp_iop_grpc/request.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1apdp_iop_grpc/request.proto\"S\n\"GetSimilarEntityOrganicFeedRequest\x12-\n\x07request\x18\x01 \x01(\x0b\x32\x1c.GetSimilarEntityFeedRequest\"N\n\x1dGetSimilarEntityCtFeedRequest\x12-\n\x07request\x18\x01 \x01(\x0b\x32\x1c.GetSimilarEntityFeedRequest\"N\n\x1dGetSimilarEntityAdFeedRequest\x12-\n\x07request\x18\x01 \x01(\x0b\x32\x1c.GetSimilarEntityFeedRequest\"9\n\x1bGetSimilarEntityFeedRequest\x12\x1a\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x0c.RequestData\"\xe0\x01\n\x0bRequestData\x12\x16\n\x0eparentEntityId\x18\x01 \x01(\x05\x12\x18\n\x10parentEntityType\x18\x02 \x01(\t\x12\x13\n\x0b\x66\x65\x65\x64\x43ontext\x18\x03 \x01(\t\x12\x0e\n\x06\x63ursor\x18\x04 \x01(\t\x12\r\n\x05limit\x18\x05 \x01(\x05\x12$\n\x04meta\x18\x06 \x03(\x0b\x32\x16.RequestData.MetaEntry\x12\x18\n\x10subSubCategoryId\x18\x07 \x01(\x05\x1a+\n\tMetaEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42;\n%com.meesho.ml.pdpiop.client.grpc.dtosZ\x12../../grpc/pdp-iopb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pdp_iop_grpc.request_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%com.meesho.ml.pdpiop.client.grpc.dtosZ\022../../grpc/pdp-iop'
  _globals['_REQUESTDATA_METAENTRY']._loaded_options = None
  _globals['_REQUESTDATA_METAENTRY']._serialized_options = b'8\001'
  _globals['_GETSIMILARENTITYORGANICFEEDREQUEST']._serialized_start=30
  _globals['_GETSIMILARENTITYORGANICFEEDREQUEST']._serialized_end=113
  _globals['_GETSIMILARENTITYCTFEEDREQUEST']._serialized_start=115
  _globals['_GETSIMILARENTITYCTFEEDREQUEST']._serialized_end=193
  _globals['_GETSIMILARENTITYADFEEDREQUEST']._serialized_start=195
  _globals['_GETSIMILARENTITYADFEEDREQUEST']._serialized_end=273
  _globals['_GETSIMILARENTITYFEEDREQUEST']._serialized_start=275
  _globals['_GETSIMILARENTITYFEEDREQUEST']._serialized_end=332
  _globals['_REQUESTDATA']._serialized_start=335
  _globals['_REQUESTDATA']._serialized_end=559
  _globals['_REQUESTDATA_METAENTRY']._serialized_start=516
  _globals['_REQUESTDATA_METAENTRY']._serialized_end=559
# @@protoc_insertion_point(module_scope)
