# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pdp_iop_grpc/response.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'pdp_iop_grpc/response.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bpdp_iop_grpc/response.proto\"V\n#GetSimilarEntityOrganicFeedResponse\x12/\n\x08response\x18\x01 \x01(\x0b\x32\x1d.GetSimilarEntityFeedResponse\"Q\n\x1eGetSimilarEntityAdFeedResponse\x12/\n\x08response\x18\x01 \x01(\x0b\x32\x1d.GetSimilarEntityFeedResponse\"Q\n\x1eGetSimilarEntityCtFeedResponse\x12/\n\x08response\x18\x01 \x01(\x0b\x32\x1d.GetSimilarEntityFeedResponse\"R\n\x1cGetSimilarEntityFeedResponse\x12\x1b\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\r.ResponseData\x12\x15\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x06.Error\"~\n\x0cResponseData\x12\x15\n\rtenantContext\x18\x01 \x01(\t\x12\x15\n\rhasNextEntity\x18\x02 \x01(\x08\x12\x31\n\x0fsimilarEntities\x18\x03 \x03(\x0b\x32\x18.SimilarEntitiesResponse\x12\r\n\x05Slots\x18\x04 \x03(\x05\"t\n\x17SimilarEntitiesResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06\x63ursor\x18\x02 \x01(\t\x12\x0c\n\x04meta\x18\x03 \x01(\t\x12\x12\n\ntrackingId\x18\x04 \x01(\t\x12\x1b\n\x08metadata\x18\x05 \x01(\x0b\x32\t.MetaData\"\xa9\x02\n\x08MetaData\x12%\n\x06scores\x18\x01 \x03(\x0b\x32\x15.MetaData.ScoresEntry\x12\x0e\n\x06source\x18\x02 \x01(\t\x12\'\n\x07\x63ontext\x18\x03 \x03(\x0b\x32\x16.MetaData.ContextEntry\x12\x11\n\tsubTenant\x18\x04 \x01(\t\x12\x1f\n\x03sse\x18\x05 \x03(\x0b\x32\x12.MetaData.SseEntry\x1a-\n\x0bScoresEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a.\n\x0c\x43ontextEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a*\n\x08SseEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x18\n\x05\x45rror\x12\x0f\n\x07message\x18\x01 \x01(\tB;\n%com.meesho.ml.pdpiop.client.grpc.dtosZ\x12../../grpc/pdp-iopb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pdp_iop_grpc.response_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%com.meesho.ml.pdpiop.client.grpc.dtosZ\022../../grpc/pdp-iop'
  _globals['_METADATA_SCORESENTRY']._loaded_options = None
  _globals['_METADATA_SCORESENTRY']._serialized_options = b'8\001'
  _globals['_METADATA_CONTEXTENTRY']._loaded_options = None
  _globals['_METADATA_CONTEXTENTRY']._serialized_options = b'8\001'
  _globals['_METADATA_SSEENTRY']._loaded_options = None
  _globals['_METADATA_SSEENTRY']._serialized_options = b'8\001'
  _globals['_GETSIMILARENTITYORGANICFEEDRESPONSE']._serialized_start=31
  _globals['_GETSIMILARENTITYORGANICFEEDRESPONSE']._serialized_end=117
  _globals['_GETSIMILARENTITYADFEEDRESPONSE']._serialized_start=119
  _globals['_GETSIMILARENTITYADFEEDRESPONSE']._serialized_end=200
  _globals['_GETSIMILARENTITYCTFEEDRESPONSE']._serialized_start=202
  _globals['_GETSIMILARENTITYCTFEEDRESPONSE']._serialized_end=283
  _globals['_GETSIMILARENTITYFEEDRESPONSE']._serialized_start=285
  _globals['_GETSIMILARENTITYFEEDRESPONSE']._serialized_end=367
  _globals['_RESPONSEDATA']._serialized_start=369
  _globals['_RESPONSEDATA']._serialized_end=495
  _globals['_SIMILARENTITIESRESPONSE']._serialized_start=497
  _globals['_SIMILARENTITIESRESPONSE']._serialized_end=613
  _globals['_METADATA']._serialized_start=616
  _globals['_METADATA']._serialized_end=913
  _globals['_METADATA_SCORESENTRY']._serialized_start=776
  _globals['_METADATA_SCORESENTRY']._serialized_end=821
  _globals['_METADATA_CONTEXTENTRY']._serialized_start=823
  _globals['_METADATA_CONTEXTENTRY']._serialized_end=869
  _globals['_METADATA_SSEENTRY']._serialized_start=871
  _globals['_METADATA_SSEENTRY']._serialized_end=913
  _globals['_ERROR']._serialized_start=915
  _globals['_ERROR']._serialized_end=939
# @@protoc_insertion_point(module_scope)
