# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pdp_iop_grpc/service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'pdp_iop_grpc/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pdp_iop_grpc import request_pb2 as pdp__iop__grpc_dot_request__pb2
from pdp_iop_grpc import response_pb2 as pdp__iop__grpc_dot_response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1apdp_iop_grpc/service.proto\x1a\x1apdp_iop_grpc/request.proto\x1a\x1bpdp_iop_grpc/response.proto2\xc0\x02\n\rPdpIopService\x12l\n\x1d\x46\x65tchExploitSimilarEntityFeed\x12#.GetSimilarEntityOrganicFeedRequest\x1a$.GetSimilarEntityOrganicFeedResponse\"\x00\x12\x62\n\x1d\x46\x65tchExploreSimilarEntityFeed\x12\x1e.GetSimilarEntityCtFeedRequest\x1a\x1f.GetSimilarEntityCtFeedResponse\"\x00\x12]\n\x18\x46\x65tchAdSimilarEntityFeed\x12\x1e.GetSimilarEntityAdFeedRequest\x1a\x1f.GetSimilarEntityAdFeedResponse\"\x00\x42\x41\n)com.meesho.ml.pdpiop.client.grpc.servicesP\x01Z\x12../../grpc/pdp-iopb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pdp_iop_grpc.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n)com.meesho.ml.pdpiop.client.grpc.servicesP\001Z\022../../grpc/pdp-iop'
  _globals['_PDPIOPSERVICE']._serialized_start=88
  _globals['_PDPIOPSERVICE']._serialized_end=408
# @@protoc_insertion_point(module_scope)
